categories:
  "2016BFC":
    "val": 0 
    "year": 2016
    "eta": "$\\eta < 0.7$"
  "2016BFF":
    "val": 1 
    "year": 2016
    "eta": "$0.7 < \\eta < 1.4$"
  "2016GHC":
    "val": 2 
    "year": 2016
    "eta": "$\\eta < 0.7$"
 
  "2016GHF":
    "val": 3
    "year": 2016
    "eta": "$0.7 < \\eta < 1.4$"
 
  "2017C": 
    "val": 4
    "year": 2017
    "eta": "$\\eta < 0.7$"
 
  "2017F":
    "val": 5
    "year": 2016
    "eta": "$0.7 < \\eta < 1.4$"
 
  "2018C": 
    "val": 6
    "year": 2018
    "eta": "$\\eta < 0.7$"
 
  "2018F":
    "val": 7
    "year": 2018
    "eta": "$0.7 < \\eta < 1.4$"
 

